from __future__ import annotations

import io
import logging

from jinja2 import Template

logger = logging.getLogger(__name__)

PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; margin: 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start;
            border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px; }
  .business-name { font-size: 24px; font-weight: 700; color: #0d9488; }
  .business-details { font-size: 12px; color: #666; margin-top: 4px; }
  .proposal-title { font-size: 28px; font-weight: 700; margin: 20px 0 10px; }
  .client-info { background: #f0fdfa; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
  .client-info strong { color: #0d9488; }
  .section { margin-bottom: 24px; }
  .section h2 { font-size: 18px; color: #0d9488; border-bottom: 1px solid #e0e0e0;
                padding-bottom: 6px; }
  .section p { line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #0d9488; color: white; padding: 10px 12px; text-align: left; }
  td { padding: 10px 12px; border-bottom: 1px solid #e0e0e0; }
  .totals { text-align: right; margin-top: 16px; }
  .totals .row { display: flex; justify-content: flex-end; gap: 40px; padding: 4px 0; }
  .totals .total { font-size: 20px; font-weight: 700; color: #0d9488; border-top: 2px solid #0d9488; padding-top: 8px; }
  .terms { background: #fafafa; padding: 16px; border-radius: 8px; margin-top: 24px;
           font-size: 13px; color: #666; }
  .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999;
            border-top: 1px solid #e0e0e0; padding-top: 16px; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="business-name">{{ business_name }}</div>
      {% if business_email or business_phone %}
      <div class="business-details">
        {{ business_email or '' }}{% if business_email and business_phone %} | {% endif %}{{ business_phone or '' }}
      </div>
      {% endif %}
      {% if business_address %}
      <div class="business-details">{{ business_address }}</div>
      {% endif %}
    </div>
    <div style="text-align: right; font-size: 12px; color: #999;">
      PROPOSAL
    </div>
  </div>

  <div class="proposal-title">{{ title }}</div>

  {% if client_name or client_company %}
  <div class="client-info">
    <strong>Prepared for:</strong><br>
    {% if client_name %}{{ client_name }}<br>{% endif %}
    {% if client_company %}{{ client_company }}<br>{% endif %}
    {% if client_email %}{{ client_email }}{% endif %}
  </div>
  {% endif %}

  {% for section in sections %}
  <div class="section">
    <h2>{{ section.title }}</h2>
    <p>{{ section.content or '' }}</p>
  </div>
  {% endfor %}

  {% if pricing_items %}
  <div class="section">
    <h2>Pricing</h2>
    <table>
      <thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead>
      <tbody>
      {% for item in pricing_items %}
        <tr>
          <td>{{ item.description }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.unit_price }}</td>
          <td>{{ item.amount }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <div class="totals">
      <div class="row"><span>Subtotal:</span> <span>{{ subtotal }}</span></div>
      {% if discount_percent %}<div class="row"><span>Discount ({{ discount_percent }}%):</span> <span>-{{ discount_amount }}</span></div>{% endif %}
      {% if tax_percent %}<div class="row"><span>Tax ({{ tax_percent }}%):</span> <span>{{ tax_amount }}</span></div>{% endif %}
      <div class="row total"><span>Total:</span> <span>{{ total }}</span></div>
    </div>
  </div>
  {% endif %}

  {% if terms %}
  <div class="terms">
    <strong>Terms & Conditions</strong><br>
    {{ terms }}
  </div>
  {% endif %}

  <div class="footer">
    Generated by DoAide Proposals | Valid for {{ validity_days }} days
  </div>
</body>
</html>
"""


def generate_pdf(proposal_data: dict) -> bytes:
    try:
        from weasyprint import HTML
        template = Template(PDF_TEMPLATE)
        html_content = template.render(**proposal_data)
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.warning("weasyprint not installed, returning HTML as fallback")
        template = Template(PDF_TEMPLATE)
        html_content = template.render(**proposal_data)
        return html_content.encode("utf-8")
    except Exception:
        logger.exception("PDF generation failed")
        raise
